application: mu-archive
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /update/.*
  script: mumusic.app
  login: admin
- url: /populate
  script: mumusic.app
  login: admin
- url: /static
  static_dir: static
- url: /.*
  script: mumusic.app
